Calculate CommitteeID when creating message IDs
ssvlabs/ssv-spec pull request #433
Opened 2024-06-27 22:21 UTC by GalRogozinski

1. Add `DomainType` to `CommitteeMember`
2. Use `DomainType` and `CommitteeID` to create MessageID in CommitteeRunner

2024-06-27 22:22 UTC, GalRogozinski commented
@lior-blox 
Note that we have `Domain` in `Config` struct (old thing Alon did).
So we can use this instead

2024-06-27 22:29 UTC, MatheusFranco99 approved these changes

2024-06-28 08:20 UTC, y0sher requested changes
Just to summarize, I think `DomainType` fits better in config than in committeeMember ( or share for that matter) since its used for everything under the same network and we're not going to have different domainTypes for different shares/members ever unless its a bug.

2024-06-30 06:58 UTC, GalRogozinski commented
@y0sher 
I agree with you. In my last discussion with @lior-blox he didn't agree to do the change the way you described.
Maybe we try to speak with him again?

2024-07-01 07:10 UTC, merged